apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fi9itj5ir-nodejs 
  janus-idp.io/tekton: fi9itj5ir-nodejs
  backstage.io/kubernetes-id: fi9itj5ir-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fi9itj5ir-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  