apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fi9itj5ir-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fi9itj5ir-nodejs 
  name: fi9itj5ir-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fi9itj5ir-nodejs 
